import "../lib/styles/globals.css";

import Link from "next/link";

import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <nav>
          <Link href="/appointments">📅 קביעת תורים</Link> |
          <Link href="/admin">🔧 ניהול תורים</Link>
        </nav> */}
        {children}
      </body>
    </html>
  );
}
